### ISSUE TITLE
Default output is unclear

### ISSUE THREAD

**Issue by dimaqq** [hauntsaninja/python_readiness#15]
```command
> uvx python_readiness
Installed 10 packages in 10ms
Determined support for 9/10 packages...
aiohttp>=3.10.9                           # has_classifier_and_explicit_wheel (existing requirement ensures support)
frozenlist>=1.4.1                         # has_classifier_and_explicit_wheel (existing requirement ensures support)
multidict>=6.1.0                          # has_classifier_and_explicit_wheel (existing requirement ensures support)
yarl>=1.13.1                              # has_classifier_and_explicit_wheel (existing requirement ensures support)
aiohappyeyeballs>=2.4.3                   # has_classifier (existing requirement ensures support)
attrs>=24.2.0                             # has_classifier (existing requirement ensures support)
idna>=3.10                                # has_classifier (existing requirement ensures support)
packaging>=24.1                           # has_classifier (existing requirement ensures support)
aiosignal>=1.3.1                          # has_viable_wheel (cannot ensure support)
python_readiness>=2.0                     # has_viable_wheel (cannot ensure support)
```

So... what does this mean?

Which is the missing package (not in 9/10)?

What Python versions are we talking about here, my projects? my venv? 

Where did `fronzenlist` come from? There's no mention of that in my project, and it's not in the venv.

**Comment by hauntsaninja** [comment]
Thanks for trying it out!

Running just `python_readiness` will check whether the versions in the current environment are compatible with the specified Python. Since you're using `uvx` to run `python_readiness` out of an isolated environment, the current environment will (not particularly helpfully) be the isolated environment. You could use the `-e` flag to specify a specific environment.

I think https://github.com/hauntsaninja/python_readiness/pull/16 should help address your feedback, please let me know if there's something else that can be improved! (Released as part of v2.1)
